const seedEvents = [
  {
    name: 'Global Tech & AI Summit 2026',
    description: 'The world\'s premier gathering of artificial intelligence pioneers, robotics engineers, cloud architects, and tech visionary executives. Featuring keynotes on generative AI, quantum computing, and ethical AI deployment.',
    category: 'Conference',
    industry: 'Technology',
    startDate: new Date('2026-10-15T09:00:00Z'),
    endDate: new Date('2026-10-18T18:00:00Z'),
    venue: 'Convention Center West Hall',
    city: 'San Francisco',
    country: 'United States',
    organizer: 'TechEx Global Ventures',
    website: 'https://globaltechsummit.io',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    status: 'UPCOMING'
  },
  {
    name: 'International Green Energy & Solar Expo',
    description: 'Discover breakthrough renewable energy solutions, solar technology innovations, EV infrastructure, and sustainable energy storage systems with over 500 exhibitors worldwide.',
    category: 'Exhibition',
    industry: 'Green Energy',
    startDate: new Date('2026-11-05T09:30:00Z'),
    endDate: new Date('2026-11-07T17:00:00Z'),
    venue: 'Messe Frankfurt Expo Center',
    city: 'Frankfurt',
    country: 'Germany',
    organizer: 'EuroClean Energy Expo Group',
    website: 'https://greenenergyexpo.de',
    image: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1200&q=80',
    status: 'UPCOMING'
  },
  {
    name: 'FinTech Innovation & Banking World Forum',
    description: 'Exploring the future of decentralized finance (DeFi), digital banking, blockchain security, ISO20022 compliance, and next-gen payment gateways.',
    category: 'Summit',
    industry: 'Finance',
    startDate: new Date('2026-09-24T08:30:00Z'),
    endDate: new Date('2026-09-26T17:30:00Z'),
    venue: 'Marina Bay Sands Expo & Convention Centre',
    city: 'Singapore',
    country: 'Singapore',
    organizer: 'Global Financial Media Network',
    website: 'https://fintechworldforum.org',
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
    status: 'ONGOING'
  },
  {
    name: 'MedHealth World Congress & Healthcare Expo',
    description: 'Bringing together medical practitioners, biotech researchers, healthtech startups, and hospital equipment leaders for groundbreaking medical discovery exchange.',
    category: 'Trade Show',
    industry: 'Healthcare',
    startDate: new Date('2026-12-01T09:00:00Z'),
    endDate: new Date('2026-12-03T18:00:00Z'),
    venue: 'Dubai World Trade Centre',
    city: 'Dubai',
    country: 'United Arab Emirates',
    organizer: 'Pan-Arab Health Exhibitions',
    website: 'https://medhealthcongress.ae',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    status: 'UPCOMING'
  },
  {
    name: 'UX/UI & Product Design Leaders Masterclass',
    description: 'Hands-on intensive masterclass and conference for senior product designers, design systems leads, accessibility experts, and design executives.',
    category: 'Workshop',
    industry: 'Design',
    startDate: new Date('2026-10-02T10:00:00Z'),
    endDate: new Date('2026-10-03T16:00:00Z'),
    venue: 'ExCeL London International Centre',
    city: 'London',
    country: 'United Kingdom',
    organizer: 'Design Forward Institute',
    website: 'https://uxdesignleaders.co.uk',
    image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    status: 'UPCOMING'
  },
  {
    name: 'CyberDefense & Cloud Security Summit',
    description: 'Annual gathering focused on zero-trust architectures, cloud security posture management (CSPM), threat intelligence, and AI-powered threat response.',
    category: 'Conference',
    industry: 'Cybersecurity',
    startDate: new Date('2026-08-10T09:00:00Z'),
    endDate: new Date('2026-08-12T17:00:00Z'),
    venue: 'Tokyo International Forum',
    city: 'Tokyo',
    country: 'Japan',
    organizer: 'Asia CyberSec Alliance',
    website: 'https://cyberdefensesummit.jp',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    status: 'COMPLETED'
  },
  {
    name: 'Smart Cities & E-Mobility Expo 2026',
    description: 'Showcasing autonomous transit systems, smart grid integration, urban planning technology, micro-mobility, and IoT infrastructure for future smart cities.',
    category: 'Trade Show',
    industry: 'Smart Cities',
    startDate: new Date('2026-11-18T09:00:00Z'),
    endDate: new Date('2026-11-20T17:30:00Z'),
    venue: 'Fira de Barcelona Gran Via',
    city: 'Barcelona',
    country: 'Spain',
    organizer: 'Urban Motion Alliance',
    website: 'https://smartcitiesexpo.es',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    status: 'UPCOMING'
  },
  {
    name: 'Global E-Commerce & Logistics Forum',
    description: 'Cross-border supply chain solutions, AI warehouse automation, last-mile delivery innovations, and omni-channel e-commerce growth strategies.',
    category: 'Summit',
    industry: 'Logistics & Retail',
    startDate: new Date('2026-10-28T09:00:00Z'),
    endDate: new Date('2026-10-30T17:00:00Z'),
    venue: 'Javits Convention Center',
    city: 'New York',
    country: 'United States',
    organizer: 'Retail Logistics Network',
    website: 'https://ecomlogisticsforum.com',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    status: 'DRAFT'
  }
];

module.exports = seedEvents;
